<?php

/**
 * TeaModel class file.
 *
 * @author tonylevid <tonylevid@gmail.com>
 * @link http://www.tframework.com/
 * @copyright http://tonylevid.com/
 * @license http://www.tframework.com/license/
 * @package base
 */
class TeaModel extends TeaCommon {

    public static $config = array(
        'defaultConnection' => 'default',
        'connections' => array(
            'default' => array(
                'dsn' => 'mysql:host=127.0.0.1;dbname=test;',
                'username' => 'root',
                'password' => '123456',
                'charset' => 'utf8', // if charset has been defined in dsn, this will be invalid.
                'tablePrefix' => 'tb_',
                'tableAliasMark' => '->',
                'persistent' => true,
                'emulatePrepare' => true,
                'autoConnect' => true,
            )
        )
    );

    /**
     * Proper TeaDbConnection subclass instance.
     * @var TeaDbConnection
     */
    public $connection;
    
    /**
     * Proper TeaDbSqlBuilder subclass instance.
     * @var TeaDbSqlBuilder
     */
    public $sqlBuilder;
    
    /**
     * Proper TeaDbSchema subclass instance.
     * @var TeaDbSchema
     */
    public $schema;
    
    /**
     * Proper TeaDbQuery subclass instance.
     * @var TeaDbQuery
     */
    public $db;
    
    /**
     * Primary key column names.
     * @var array
     */
    private $_pkColNames = array();

    /**
     * Constructor, set properties for instances.
     */
    public function __construct() {
        $this->setClassConfig(__CLASS__);
        $this->connection = $this->getDbConnection();
        $this->db = $this->getDbQuery();
        $this->sqlBuilder = $this->getDbSqlBuilder();
        $this->schema = $this->getDbSchema();
    }
    
    /**
     * Hook method.
     * Return the table name for this model. Defaults to the lowercased and underscored model name.
     * @return string Table name.
     */
    public function tableName() {
        $className = get_class($this);
        return StringHelper::camelToUnderscore(preg_replace('/(.+)Model/', '$1', $className));
    }

    /**
     * Get real table name. 
     * If Table name is '{{table_name}}', and table prefix is 'tbl_'. This will return 'tbl_table_name'.
     * @return string Real table name
     */
    public function getTableName() {
        return $this->sqlBuilder->getTableName($this->tableName());
    }

    public function getTableAlias() {
        return $this->sqlBuilder->getTableAlias($this->tableName());
    }
    
    /**
     * Insert record(s).
     * @param mixed $vals Value indicates the inserted data.
     * <pre>
     * There are three types of the vals:
     * One dimensional array:
     * array(col1Val, col2Val, colNVal, ...)
     * or 
     * array(
     *     'col1Name' => col1Val, 
     *     'col2Name' => col2Val, 
     *     'colNName' => colNVal, 
     *     ...
     * )
     * 
     * Two dimensional array:
     * array(
     *     array(col1Val, col2Val, colNVal),
     *     array(col1Val, col2Val, colNVal),
     *     ...
     * )
     * or
     * array(
     *     array('col1Name' => col1Val, 'col2Name' => col2Val, 'colNName' => colNVal),
     *     array('col1Name' => col1Val, 'col2Name' => col2Val, 'colNName' => colNVal),
     *     ... // all keys should be same as the first element array or just leave the keys of other elements empty except first.
     * )
     * 
     * Select sql string, could be generated by TeaDbSqlBuilder::select():
     * 'SELECT * FROM `table`'
     * </pre>
     * @param mixed $duplicateUpdate Update data on duplicate key occurs.
     * <pre>
     * The values will be like this:
     * array(
     *     'colName1' => colVal1,
     *     'colName2' => colVal2,
     *     ...
     * )
     * </pre>
     * @return bool
     */
    public function insert($vals, $duplicateUpdate = null) {
        $criteria = is_array($duplicateUpdate) && !empty($duplicateUpdate) ? array('duplicateUpdate' => $duplicateUpdate) : null;
        $sql = $this->sqlBuilder->insert($this->tableName(), $vals, $criteria);
        if ($this->db->query($sql)->getRowCount() > 0) {
            return true;
        }
        return false;
    }
    
    /**
     * Find a single record with the specified criteria.
     * @param mixed $criteria TeaDbCriteriaBuilder instance or criteria array.
     * @return array
     */
    public function find($criteria = null) {
        $sql = $this->sqlBuilder->select($this->tableName(), null, $criteria);
        $rst = $this->db->query($sql)->fetchRow();
        return $rst;
    }
    
    /**
     * Find a single record with the specified primary key value.
     * @param mixed $pkVal Primary key value or array values for multiple primary keys.
     * @return array
     */
    public function findByPk($pkVal) {
        return $this->find($this->getPkCriteria($pkVal));
    }
    
    /**
     * Find a single column value with the specified criteria.
     * @param string $colName Column name.
     * @param mixed $criteria TeaDbCriteriaBuilder instance or criteria array.
     * @return mixed Return column value on success, null on failure.
     */
    public function findColumn($colName, $criteria = null) {
        $sql = $this->sqlBuilder->select($this->tableName(), $colName, $criteria);
        $rst = $this->db->query($sql)->fetchRow();
        if (is_array($rst) && is_string($colName) && isset($rst[$colName])) {
            return $rst[$colName];
        }
        return null;
    }
    
    /**
     * Find a single record with the specified column names and criteria.
     * @param array $colNames Column names.
     * @param mixed $criteria TeaDbCriteriaBuilder instance or criteria array.
     * @return array
     */
    public function findColumns($colNames, $criteria = null) {
        $sql = $this->sqlBuilder->select($this->tableName(), $colNames, $criteria);
        $rst = $this->db->query($sql)->fetchRow();
        return $rst;
    }
    
    /**
     * Find all records with the specified criteria.
     * @param mixed $criteria TeaDbCriteriaBuilder instance or criteria array.
     * @return array
     */
    public function findAll($criteria = null) {
        $sql = $this->sqlBuilder->select($this->tableName(), null, $criteria);
        $rst = $this->db->query($sql)->fetchRows();
        return $rst;
    }
    
    /**
     * Update record(s) with the specified criteria.
     * @param array $vals An array indicates update data.
     * <pre>
     * It will be an array like this:
     * array(
     *     'colName1' => colVal1
     *     'colName2' => colVal2,
     *     ...
     * )
     * </pre>
     * @param mixed $criteria TeaDbCriteriaBuilder instance or criteria array. If empty, it will only update one record for safety.
     * @return bool
     */
    public function update($vals, $criteria) {
        empty($criteria) && ($criteria['limit'] = array(1));
        $sql = $this->sqlBuilder->update($this->tableName(), $vals, $criteria);
        if ($this->db->query($sql)->getRowCount() > 0) {
            return true;
        }
        return false;
    }
    
    /**
     * Update a single record with the specified primary key value.
     * @param array $vals An array indicates update data.
     * <pre>
     * It will be an array like this:
     * array(
     *     'colName1' => colVal1
     *     'colName2' => colVal2,
     *     ...
     * )
     * </pre>
     * @param mixed $pkVal Primary key value or array values for multiple primary keys.
     * @return bool
     */
    public function updateByPk($vals, $pkVal) {
        return $this->update($vals, $this->getPkCriteria($pkVal));
    }
    
    /**
     * Delete record(s) with the specified criteria.
     * @param mixed $criteria TeaDbCriteriaBuilder instance or criteria array. If empty, it will only delete one record for safety.
     * @return bool 
     */
    public function delete($criteria) {
        empty($criteria) && ($criteria['limit'] = array(1));
        $sql = $this->sqlBuilder->delete($this->tableName(), $criteria);
        if ($this->db->query($sql)->getRowCount() > 0) {
            return true;
        }
        return false;
    }
    
    /**
     * Delete a single record with the specified primary key value.
     * @param mixed $pkVal Primary key value or array values for multiple primary keys.
     * @return bool 
     */
    public function deleteByPk($pkVal) {
        return $this->delete($this->getPkCriteria($pkVal));
    }
    
    /**
     * Get the number of rows affected by the last INSERT, SELECT, UPDATE or DELETE statement.
     * @return int
     */
    public function getRowCount() {
        return $this->db->getRowCount();
    }
    
    /**
     * Get last insert id.
     * Notice: it is not support insert many rows at one time.
     * @return int Last insert id.
     */
    public function getLastInsertId() {
        return $this->db->getLastInsertId();
    }

    /**
     * Get last query sql statement.
     * @return string Sql statement.
     */
    public function getLastSql() {
        return $this->db->getLastSql();
    }
    
    /**
     * Get 'PRIMARY' index column names.
     * @return array 'PRIMARY' index column names.
     */
    protected function getPkColumnNames() {
        if (is_array($this->_pkColNames) && !empty($this->_pkColNames)) {
            return $this->_pkColNames;
        }
        return $this->_pkColNames = $this->schema->getPkColumnNames($this->tableName());
    }
    
    /**
     * Get criteria array of the primary key value.
     * @param mixed $pkVal Primary key value or array values for multiple primary keys.
     * @return array Criteria array.
     */
    protected function getPkCriteria($pkVal) {
        $criteria = array();
        $pkColNames = $this->getPkColumnNames();
        if (is_array($pkVal)) {
            if (count($pkColNames) !== count($pkVal)) {
                $pkValStr = implode(', ', $pkColNames);
                throw new TeaDbException("PRIMARY key columns array({$pkValStr}) and parameter 1 should have an equal number of elements.");
            }
            $where = array_combine($pkColNames, $pkVal);
            $criteria = array('where' => $where);
        } else {
            $criteria = array('where' => array($pkColNames[0] => $pkVal));
        }
        return $criteria;
    }
    
}