<?php

/**
 * TeaModel class file.
 *
 * @author tonylevid <tonylevid@gmail.com>
 * @link http://www.tframework.com/
 * @copyright http://tonylevid.com/
 * @license http://www.tframework.com/license/
 * @package base
 * @property-read TeaDbCriteriaBuilder $criteria Proper TeaDbCriteriaBuilder subclass new instance.
 */
class TeaModel extends TeaCommon {

    public static $config = array(
        'defaultConnection' => 'default',
        'connections' => array(
            'default' => array(
                'dsn' => 'mysql:host=127.0.0.1;dbname=test;',
                'username' => 'root',
                'password' => '123456',
                'charset' => 'utf8', // if charset has been defined in dsn, this will be invalid.
                'tablePrefix' => 'tb_',
                'tableAliasMark' => '->',
                'persistent' => true,
                'emulatePrepare' => true,
                'autoConnect' => true,
            )
        )
    );

    /**
     * Proper TeaDbConnection subclass instance.
     * @var TeaDbConnection
     */
    public $connection;
    
    /**
     * Proper TeaDbSqlBuilder subclass instance.
     * @var TeaDbSqlBuilder
     */
    public $sqlBuilder;
    
    /**
     * Proper TeaDbSchema subclass instance.
     * @var TeaDbSchema
     */
    public $schema;
    
    /**
     * Proper TeaDbQuery subclass instance.
     * @var TeaDbQuery
     */
    public $db;
    
    /**
     * Primary key column names.
     * @var array
     */
    private $_pkColNames = array();

    /**
     * Constructor, set properties for instances.
     */
    public function __construct() {
        $this->setClassConfig(__CLASS__);
        $this->connection = $this->getDbConnection();
        $this->db = $this->getDbQuery();
        $this->sqlBuilder = $this->getDbSqlBuilder();
        $this->schema = $this->getDbSchema();
    }

    /**
     * Magic method __get.
     * This method is for getting proper TeaDbCriteriaBuilder subclass new instance.
     * @param string $name Property name.
     * @return mixed
     */
    public function __get($name) {
        if ($name === 'criteria') {
            return $this->getDbCriteriaBuilder();
        } else {
            $trace = debug_backtrace();
            trigger_error("Undefined property via __get(): {$name} in {$trace[0]['file']} on line {$trace[0]['line']}");
            return null;
        }
    }
    
    /**
     * Hook method.
     * Return the table name for this model. Defaults to the lowercased and underscored model name.
     * @return string Table name.
     */
    public function tableName() {
        $className = get_class($this);
        return StringHelper::camelToUnderscore(preg_replace('/(.+)Model/', '$1', $className));
    }

    /**
     * Get real table name. 
     * If Table name is '{{table_name}}', and table prefix is 'tbl_'. This will return 'tbl_table_name'.
     * @return string Real table name
     */
    public function getTableName() {
        return $this->sqlBuilder->getTableName($this->tableName());
    }

    /**
     * Get table alias name.
     * If $tblName is '{{table_name->A}}', This will return 'A'.
     * @param string $tblName Table name.
     * @return string Table alias name.
     */
    public function getTableAlias() {
        return $this->sqlBuilder->getTableAlias($this->tableName());
    }
    
    /**
     * Insert record(s).
     * @param mixed $vals Value indicates the inserted data.
     * <pre>
     * There are three types of the vals:
     * One dimensional array:
     * array(col1Val, col2Val, colNVal, ...)
     * or 
     * array(
     *     'col1Name' => col1Val, 
     *     'col2Name' => col2Val, 
     *     'colNName' => colNVal, 
     *     ...
     * )
     * 
     * Two dimensional array:
     * array(
     *     array(col1Val, col2Val, colNVal),
     *     array(col1Val, col2Val, colNVal),
     *     ...
     * )
     * or
     * array(
     *     array('col1Name' => col1Val, 'col2Name' => col2Val, 'colNName' => colNVal),
     *     array('col1Name' => col1Val, 'col2Name' => col2Val, 'colNName' => colNVal),
     *     ... // all keys should be same as the first element array or just leave the keys of other elements empty except first.
     * )
     * 
     * Select sql string, could be generated by TeaDbSqlBuilder::select():
     * 'SELECT * FROM `table`'
     * </pre>
     * @param mixed $duplicateUpdate Update data on duplicate key occurs.
     * <pre>
     * The values will be like this:
     * array(
     *     'colName1' => colVal1,
     *     'colName2' => colVal2,
     *     ...
     * )
     * </pre>
     * @return bool
     */
    public function insert($vals, $duplicateUpdate = null) {
        $criteria = is_array($duplicateUpdate) && !empty($duplicateUpdate) ? array('duplicateUpdate' => $duplicateUpdate) : null;
        $sql = $this->sqlBuilder->insert($this->tableName(), $vals, $criteria);
        if ($this->db->query($sql)->getRowCount() > 0) {
            return true;
        }
        return false;
    }
    
    /**
     * Find a single record with the specified criteria.
     * @param mixed $criteria TeaDbCriteriaBuilder instance or criteria array.
     * @param mixed $colName Select exprs, string or array. If empty, it will be '*'.
     * @return array
     */
    public function find($criteria = null, $colName = null) {
        $sql = $this->sqlBuilder->select($this->tableName(), $criteria, $colName);
        $rst = $this->db->query($sql)->fetchRow();
        return $rst;
    }

    /**
     * Find a single record by sql.
     * @param string $sql Sql statement.
     * @param array $params An array of values with as many elements as there are bound parameters in the sql being executed.
     * @return array
     */
    public function findBySql($sql, $params = array()) {
        $rst = $this->db->query($sql, $params)->fetchRow();
        return $rst;
    }

    /**
     * Find a single record with the condition array of criteria where.
     * @param array $condition Condition array of criteria where.
     * @param mixed $colName Select exprs, string or array. If empty, it will be '*'.
     * @return array
     */
    public function findByCondition($condition = null, $colName = null) {
        $criteria = !empty($condition) ? array('where' => $condition) : null;
        return $this->find($criteria, $colName);
    }
    
    /**
     * Find a single record with the specified primary key value.
     * @param mixed $pkVal Primary key value or array values for multiple primary keys.
     * @param mixed $colName Select exprs, string or array. If empty, it will be '*'.
     * @return array
     */
    public function findByPk($pkVal, $colName = null) {
        return $this->find($this->getPkCriteria($pkVal), $colName);
    }
    
    /**
     * Find a single record column value or multiple columns values array with the specified criteria.
     * @param mixed $criteria TeaDbCriteriaBuilder instance or criteria array.
     * @param mixed $colName Select exprs, string or array. If empty, it will be '*'.
     * @return mixed Return a single column value or multiple columns values array.
     */
    public function findColumn($criteria = null, $colName = null) {
        $sql = $this->sqlBuilder->select($this->tableName(), $criteria, $colName);
        $rst = $this->db->query($sql)->fetchRow();
        if (is_array($rst) && is_string($colName) && isset($rst[$colName])) {
            return $rst[$colName];
        } else {
            return $rst;
        }
    }

    /**
     * Find a single record column value or multiple columns values array with the condition array of criteria where.
     * @param array $condition Condition array of criteria where.
     * @param mixed $colName Select exprs, string or array. If empty, it will be '*'.
     * @return mixed Return a single column value or multiple columns values array.
     */
    public function findColumnByCondition($condition = null, $colName = null) {
        $criteria = !empty($condition) ? array('where' => $condition) : null;
        return $this->findColumn($criteria, $colName);
    }
    
    /**
     * Find all records with the specified criteria.
     * @param mixed $criteria TeaDbCriteriaBuilder instance or criteria array.
     * @param mixed $colName Select exprs, string or array. If empty, it will be '*'.
     * @return array
     */
    public function findAll($criteria = null, $colName = null) {
        $sql = $this->sqlBuilder->select($this->tableName(), $criteria, $colName);
        $rst = $this->db->query($sql)->fetchRows();
        return $rst;
    }

    /**
     * Find all records by sql.
     * @param string $sql Sql statement.
     * @param array $params An array of values with as many elements as there are bound parameters in the sql being executed.
     * @return array
     */
    public function findAllBySql($sql, $params = array()) {
        $rst = $this->db->query($sql, $params)->fetchRows();
        return $rst;
    }

    /**
     * Find all records with the condition array of criteria where.
     * @param array $condition Condition array of criteria where.
     * @param mixed $colName Select exprs, string or array. If empty, it will be '*'.
     * @return array
     */
    public function findAllByCondition($condition = null, $colName = null) {
        $criteria = !empty($condition) ? array('where' => $condition) : null;
        return $this->findAll($criteria, $colName);
    }
    
    /**
     * Update record(s) with the specified criteria.
     * @param mixed $criteria TeaDbCriteriaBuilder instance or criteria array. If empty, it will only update one record for safety.
     * @param array $vals An array indicates update data.
     * <pre>
     * It will be an array like this:
     * array(
     *     'colName1' => colVal1
     *     'colName2' => colVal2,
     *     ...
     * )
     * </pre>
     * @return bool
     */
    public function update($criteria, $vals) {
        empty($criteria) && ($criteria['limit'] = array(1));
        $sql = $this->sqlBuilder->update($this->tableName(), $vals, $criteria);
        if ($this->db->query($sql)->getRowCount() > 0) {
            return true;
        }
        return false;
    }

    /**
     * Update record(s) with the condition array of criteria where.
     * @param array $condition Condition array of criteria where. If empty, it will only update one record for safety.
     * @param array $vals An array indicates update data.
     * <pre>
     * It will be an array like this:
     * array(
     *     'colName1' => colVal1
     *     'colName2' => colVal2,
     *     ...
     * )
     * </pre>
     * @return bool
     */
    public function updateByCondition($condition, $vals) {
        $criteria = array('where' => $condition);
        return $this->update($criteria, $vals);
    }
    
    /**
     * Update a single record with the specified primary key value.
     * @param mixed $pkVal Primary key value or array values for multiple primary keys.
     * @param array $vals An array indicates update data.
     * <pre>
     * It will be an array like this:
     * array(
     *     'colName1' => colVal1
     *     'colName2' => colVal2,
     *     ...
     * )
     * </pre>
     * @return bool
     */
    public function updateByPk($pkVal, $vals) {
        return $this->update($this->getPkCriteria($pkVal), $vals);
    }

    /**
     * Increase a single record column value with the specified criteria.
     * @param mixed $criteria TeaDbCriteriaBuilder instance or criteria array.
     * @param string $colName Column name of the increment field.
     * @param int $val Value of increment, defaults to 1.
     * @return bool
     */
    public function inc($criteria, $colName, $val = 1) {
        $expr = $this->sqlBuilder->quoteColumn($colName) . ' + ' . $this->db->escape($val);
        $vals = array(
            $colName => new TeaDbExpr($expr)
        );
        return $this->update($criteria, $vals);
    }

    /**
     * Increase a single record column value with the condition array of criteria where.
     * @param array $condition Condition array of criteria where.
     * @param string $colName Column name of the increment field.
     * @param int $val Value of increment, defaults to 1.
     * @return bool
     */
    public function incByCondition($condition, $colName, $val = 1) {
        $criteria = array('where' => $condition);
        return $this->inc($criteria, $colName, $val);
    }

    /**
     * Increase a single record column value with the specified primary key value.
     * @param mixed $pkVal Primary key value or array values for multiple primary keys.
     * @param string $colName Column name of the increment field.
     * @param int $val Value of increment, defaults to 1.
     * @return bool
     */
    public function incByPk($pkVal, $colName, $val = 1) {
        return $this->inc($this->getPkCriteria($pkVal), $colName, $val);
    }
    
    /**
     * Delete record(s) with the specified criteria.
     * @param mixed $criteria TeaDbCriteriaBuilder instance or criteria array. If empty, it will only delete one record for safety.
     * @return bool 
     */
    public function delete($criteria) {
        empty($criteria) && ($criteria['limit'] = array(1));
        $sql = $this->sqlBuilder->delete($this->tableName(), $criteria);
        if ($this->db->query($sql)->getRowCount() > 0) {
            return true;
        }
        return false;
    }

    /**
     * Delete record(s) with the condition array of criteria where.
     * @param array $condition Condition array of criteria where. If empty, it will only delete one record for safety.
     * @return bool 
     */
    public function deleteByCondition($condition) {
        $criteria = array('where' => $condition);
        return $this->delete($criteria);
    }
    
    /**
     * Delete a single record with the specified primary key value.
     * @param mixed $pkVal Primary key value or array values for multiple primary keys.
     * @return bool 
     */
    public function deleteByPk($pkVal) {
        return $this->delete($this->getPkCriteria($pkVal));
    }
    
    /**
     * Get the number of rows affected by the last INSERT, SELECT, UPDATE or DELETE statement.
     * @return int
     */
    public function getRowCount() {
        return $this->db->getRowCount();
    }
    
    /**
     * Get last insert id.
     * Notice: it is not support insert many rows at one time.
     * @return int Last insert id.
     */
    public function getLastInsertId() {
        return $this->db->getLastInsertId();
    }

    /**
     * Get last query sql statement.
     * @return string Sql statement.
     */
    public function getLastSql() {
        return $this->db->getLastSql();
    }
    
    /**
     * Get 'PRIMARY' index column names.
     * @return array 'PRIMARY' index column names.
     */
    protected function getPkColumnNames() {
        if (is_array($this->_pkColNames) && !empty($this->_pkColNames)) {
            return $this->_pkColNames;
        }
        return $this->_pkColNames = $this->schema->getPkColumnNames($this->tableName());
    }
    
    /**
     * Get criteria array of the primary key value.
     * @param mixed $pkVal Primary key value or array values for multiple primary keys.
     * @return array Criteria array.
     */
    protected function getPkCriteria($pkVal) {
        $criteria = array();
        $pkColNames = $this->getPkColumnNames();
        if (is_array($pkVal)) {
            if (count($pkColNames) !== count($pkVal)) {
                $pkValStr = implode(', ', $pkColNames);
                throw new TeaDbException("PRIMARY key columns array({$pkValStr}) and parameter 1 should have an equal number of elements.");
            }
            $where = array_combine($pkColNames, $pkVal);
            $criteria = array('where' => $where);
        } else {
            $criteria = array('where' => array($pkColNames[0] => $pkVal));
        }
        return $criteria;
    }
    
}